### ISSUE TITLE
magic.open ERROR. AttributeError: 'module' object has no attribute 'open

### ISSUE THREAD

**Issue by sandikast** [dbrumley/redebug#1]
Hi, I have trouble in running this project under Python2.7
`user@user:~/git/redebug$ python redebug.py /home/user/xxx /home/user/xxx
Traceback (most recent call last):
  File "redebug.py", line 65, in <module>
    common.magic_cookie = magic.open(magic.MAGIC_MIME)
AttributeError: 'module' object has no attribute 'open'`

I found that in my magic.py, there is no method named "magic.open", and I want to know how to fix this. Thanks

**Comment by souljang** [comment]
Thanks for letting us know the issue. Apparently, there are different `magic` modules, which causes an AttributeError. I've added support for different magic modules.

**Comment by sandikast** [comment]
Thanks a lot @jiyongj
